const first = [
  {
    key: 'ё',
    code: 'Backquote',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,

  },
  {
    key: '1',
    code: 'Digit1',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '!',
  },
  {
    key: '2',
    code: 'Digit2',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '"',
  },
  {
    key: '3',
    code: 'Digit3',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '№',
  },
  {
    key: '4',
    code: 'Digit4',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: ';',
  },
  {
    key: '5',
    code: 'Digit5',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '%',
  },
  {
    key: '6',
    code: 'Digit6',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: ':',
  },
  {
    key: '7',
    code: 'Digit7',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '?',
  },
  {
    key: '8',
    code: 'Digit8',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '*',
  },
  {
    key: '9',
    code: 'Digit9',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '(',
  },
  {
    key: '0',
    code: 'Digit0',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: ')',
  },
  {
    key: '-',
    code: 'Minus',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '_',
  },
  {
    key: '=',
    code: 'Equal',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '+',
  },

  {
    key: 'Backspace',
    code: 'Backspace',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const second = [
  {
    key: 'Tab',
    code: 'Tab',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'й',
    code: 'KeyQ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ц',
    code: 'KeyW',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'у',
    code: 'KeyE',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'к',
    code: 'KeyR',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'е',
    code: 'KeyT',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'н',
    code: 'KeyY',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'г',
    code: 'KeyU',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ш',
    code: 'KeyI',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'щ',
    code: 'KeyO',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'з',
    code: 'KeyP',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'х',
    code: 'BracketLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ъ',
    code: 'BracketRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: '\\',
    code: 'Backslash',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '/',
  },
  {
    key: 'Delete',
    code: 'Delete',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const third = [
  {
    key: 'CapsLock',
    code: 'CapsLock',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ф',
    code: 'KeyA',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ы',
    code: 'KeyS',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'в',
    code: 'KeyD',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'а',
    code: 'KeyF',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'п',
    code: 'KeyG',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'р',
    code: 'KeyH',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'о',
    code: 'KeyJ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'л',
    code: 'KeyK',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'д',
    code: 'KeyL',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ж',
    code: 'Semicolon',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'э',
    code: 'Quote',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Enter',
    code: 'Enter',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const fourth = [
  {
    key: 'Shift',
    code: 'ShiftLeft',
    ctrlKey: false,
    shiftKey: true,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'я',
    code: 'KeyZ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ч',
    code: 'KeyX',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'с',
    code: 'KeyC',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'м',
    code: 'KeyV',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'и',
    code: 'KeyB',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'т',
    code: 'KeyN',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ь',
    code: 'KeyM',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'б',
    code: 'Comma',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ю',
    code: 'Period',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: '.',
    code: 'Slash',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ArrowUp',
    code: 'ArrowUp',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Shift',
    code: 'ShiftRight',
    ctrlKey: false,
    shiftKey: true,
    altKey: false,
    metaKey: false,
  },
];
const fifth = [
  {
    key: 'Control',
    code: 'ControlLeft',
    ctrlKey: true,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Meta',
    code: 'MetaLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: true,
  },
  {
    key: 'Alt',
    code: 'AltLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: true,
    metaKey: false,
  },
  {
    key: ' ',
    code: 'Space',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Alt',
    code: 'AltRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: true,
    metaKey: false,
  },
  {
    key: 'ArrowLeft',
    code: 'ArrowLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  }, {
    key: 'ArrowDown',
    code: 'ArrowDown',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  }, {
    key: 'ArrowRight',
    code: 'ArrowRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Control',
    code: 'ControlRight',
    ctrlKey: true,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const keys = [
  first, second, third, fourth, fifth,
];
export default keys;
