const first = [
  {
    key: '`',
    code: 'Backquote',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '~',
  },
  {
    key: '1',
    code: 'Digit1',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '!',
  },
  {
    key: '2',
    code: 'Digit2',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '@',
  },
  {
    key: '3',
    code: 'Digit3',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '#',
  },
  {
    key: '4',
    code: 'Digit4',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '$',
  },
  {
    key: '5',
    code: 'Digit5',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '%',
  },
  {
    key: '6',
    code: 'Digit6',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '^',
  },
  {
    key: '7',
    code: 'Digit7',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '&',
  },
  {
    key: '8',
    code: 'Digit8',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '*',
  },
  {
    key: '9',
    code: 'Digit9',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '(',
  },
  {
    key: '0',
    code: 'Digit0',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: ')',
  },
  {
    key: '-',
    code: 'Minus',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '_',
  },
  {
    key: '=',
    code: 'Equal',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '+',
  },
  {
    key: '\\',
    code: 'Backslash',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
    secondValue: '~',
  },
  {
    key: 'Backspace',
    code: 'Backspace',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const second = [
  {
    key: 'Tab',
    code: 'Tab',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'q',
    code: 'KeyQ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'w',
    code: 'KeyW',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'e',
    code: 'KeyE',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'r',
    code: 'KeyR',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 't',
    code: 'KeyT',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'y',
    code: 'KeyY',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'u',
    code: 'KeyU',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'i',
    code: 'KeyI',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'o',
    code: 'KeyO',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'p',
    code: 'KeyP',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: '[',
    code: 'BracketLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: ']',
    code: 'BracketRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Enter',
    code: 'Enter',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const third = [
  {
    key: 'CapsLock',
    code: 'CapsLock',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'a',
    code: 'KeyA',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 's',
    code: 'KeyS',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'd',
    code: 'KeyD',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'f',
    code: 'KeyF',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'g',
    code: 'KeyG',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'h',
    code: 'KeyH',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'j',
    code: 'KeyJ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'k',
    code: 'KeyK',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'l',
    code: 'KeyL',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: ';',
    code: 'Semicolon',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: "'",
    code: 'Quote',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Enter',
    code: 'Enter',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const fourth = [
  {
    key: 'Shift',
    code: 'ShiftLeft',
    ctrlKey: false,
    shiftKey: true,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'z',
    code: 'KeyZ',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'x',
    code: 'KeyX',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'c',
    code: 'KeyC',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'v',
    code: 'KeyV',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'b',
    code: 'KeyB',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'n',
    code: 'KeyN',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'm',
    code: 'KeyM',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: ',',
    code: 'Comma',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: '.',
    code: 'Period',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: '/',
    code: 'Slash',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ArrowUp',
    code: 'ArrowUp',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Shift',
    code: 'ShiftRight',
    ctrlKey: false,
    shiftKey: true,
    altKey: false,
    metaKey: false,
  },
];
const fifth = [
  {
    key: 'Control',
    code: 'ControlLeft',
    ctrlKey: true,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Meta',
    code: 'MetaLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: true,
  },
  {
    key: 'Alt',
    code: 'AltLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: true,
    metaKey: false,
  },
  {
    key: ' ',
    code: 'Space',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Alt',
    code: 'AltRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: true,
    metaKey: false,
  },
  {
    key: 'Meta',
    code: 'MetaRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: true,
  },
  {
    key: 'ContextMenu',
    code: 'ContextMenu',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'ArrowLeft',
    code: 'ArrowLeft',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  }, {
    key: 'ArrowDown',
    code: 'ArrowDown',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  }, {
    key: 'ArrowRight',
    code: 'ArrowRight',
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
  {
    key: 'Control',
    code: 'ControlRight',
    ctrlKey: true,
    shiftKey: false,
    altKey: false,
    metaKey: false,
  },
];
const keys = [
  first, second, third, fourth, fifth,
];
export default keys;
